# Generated by Django 4.2.2 on 2023-06-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Titre')),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
