# Generated by Django 4.2.2 on 2023-07-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='media/thumbnails'),
        ),
    ]
